version: '3.5'

networks:
   web-ctm-app-net:
       name: my-ctm-web-app-net
       driver: bridge

services:
   frontend:
     container_name:
     image: devopsibcs/ctm:ctm-staging-frontend-service-1.0.0
     environment:
            - TZ=Asia/Dhaka
     ports:
       - 3080:80
     restart: always
     build:
         context: "./"
         dockerfile: "Dockerfile"
 
     networks:
       - web-ctm-app-net
##End of Scripts
