version: '3.5'

networks:
   web-ctm-app-net:
       name: my-ctm-web-app-net
       driver: bridge

services:
   frontend:
     container_name: ctm-frontend
     image: 'ctm-frontend'
     environment:
            - TZ=Asia/Dhaka
     ports:
       - 3007:3000
     restart: always
     build:
         context: "./"
         dockerfile: "Dockerfile"
 
     networks:
       - web-ctm-app-net
##End of Scripts
