version: '4.0'
services:
  frontend:
    container_name: ctm-frontend
    image: 'frontend'
    environment:
      - TZ=Asia/Dhaka
    networks:
      - ppims_net
    ports:
      - 8070:80
    restart: always
    build:
      context: "./"
      dockerfile: "Dockerfile"

    networks:
   ppims_net:
     name: ppims_net
##End of Scripts
