version: '3.5'
services:
   frontend:
     container_name: ctm-frontend
     image: 'ctm-app-frontend'
     environment:
            - TZ=Asia/Dhaka
     ports:
       - 3000:8080
     restart: always
     build:
         context: "./"
         dockerfile: "Dockerfile"
 
     networks:
        web-ctm-app-net:
           name: web-ctm-app-net
##End of Scripts
