version: '3.0'

services:
  frontend-stage:
    container_name: ctm-frontend-stage
    image: 'ctm-app-frontend-stage'

    environment:
      - TZ=Asia/Dhaka
    networks:
      - ppims_net

    ports:
      - 8060:80
    restart: always
    build:
      context: "./"
      dockerfile: "Dockerfile"

    networks:
      - web-ctm-app-net
##End of Scripts
