version: '3.0'

services:
  frontend-stage:
    container_name: ctm-frontend
    image: 'ctm-app-frontend'
    environment:
      - TZ=Asia/Dhaka
    networks:
      - ppmis_net

    ports:
      - 8070:80
    restart: always
    build:
      context: "./"
      dockerfile: "Dockerfile"

networks:
   ppmis_net:
     name: ppmis_net

