version: '3.5'

networks:
  web-ctm-app-net:
    name: my-ctm-web-app-net
    driver: bridge
    external: true

services:
  frontend-stage:
    container_name: ctm-frontend
    image: 'ctm-app-frontend'
    environment:
      - TZ=Asia/Dhaka
    ports:
      - 8070:80
    restart: always
    build:
      context: "./"
      dockerfile: "Dockerfile"

    networks:
      - web-ctm-app-net
##End of Scripts
